sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 200510qq.
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPiLaP8sMxTqe9iVgRP
    access-key-secret: 97BN0J0lgkWUWS9JO6tGrk12CNqaEf
    bucket-name: hikaritext
  redis:
    host: localhost
    port: 6379
    database: 0
  
  wechat:
    appid: wxbb98e0d99aa8132f
    secret: e64d88994c1f8a014404c5d074db40f9
    notify-url: https://28b202cd.r11.cpolar.top
    refund-notify-url: https://28b202cd.r11.cpolar.top

  baidu:
    shop: 北京市海滨区上地十街10号
    ak: ZtlcVroZELJTv6p6NuvHVk7tXTi9rxXe
    geocidubg-url: http://api.map.baidu.com/geocoding/v3/?address={address}&output=json&ak={ak}
    max-delivery: 5000
    shop-coordinates: "40.057031,116.307852"
    planning-url: "https://api.map.baidu.com/direction/v2/riding?origin={origin}&destination={destination}&ak={ak}"